feat(credential offer)
jolocom/jolocom-sdk pull request #100
Opened 2021-03-16 13:45 UTC by SBub

returning signed credential on credential store

2021-03-16 14:48 UTC, clauxx approved these changes

2021-03-16 15:50 UTC, mnzaki requested changes

2021-03-16 15:50 UTC, mnzaki commented on src/interactionManager/interaction.ts
> +          this.ctx.ctx.storage.store.verifiableCredential(cred)
need to await this promise, since it's not being returned anymore

2021-03-17 10:42 UTC, mnzaki approved these changes
:+1:

2021-03-17 11:02 UTC, merged